INSERT INTO DimStation (Stationid,City) VALUES (19,'Sao Paulo');
INSERT INTO DimStation (Stationid,City) VALUES (21,'Sao Paulo');
INSERT INTO DimStation (Stationid,City) VALUES (31,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (32,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (40,'Brasilia');
INSERT INTO DimStation (Stationid,City) VALUES (43,'Brasilia');
INSERT INTO DimStation (Stationid,City) VALUES (44,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (46,'Brasilia');
INSERT INTO DimStation (Stationid,City) VALUES (47,'Salvador');
INSERT INTO DimStation (Stationid,City) VALUES (48,'Salvador');
INSERT INTO DimStation (Stationid,City) VALUES (57,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (71,'Brasilia');
INSERT INTO DimStation (Stationid,City) VALUES (77,'Brasilia');
INSERT INTO DimStation (Stationid,City) VALUES (81,'Salvador');
INSERT INTO DimStation (Stationid,City) VALUES (82,'Salvador');
INSERT INTO DimStation (Stationid,City) VALUES (83,'Sao Paulo');
INSERT INTO DimStation (Stationid,City) VALUES (84,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (86,'Rio de Janeiro');
INSERT INTO DimStation (Stationid,City) VALUES (97,'Brasilia');
